### ISSUE TITLE
link to slides broken

### ISSUE THREAD

**Issue by cmungall** [EBIBioSamples/myequivalents#3]
https://github.com/EBIBioSamples/myequivalents/wiki/Architecture

Links to a local server

**Comment by marco-brandizi** [comment]
Hi Chris, 

sorry, for some reason, I believed I had updated that [link](http://www.slideshare.net/mbrandizi/myequivalents-pres-20130214). I've done it now. The slides are a bit outdated in the details, but still valid in the general concepts. 

Please let me know what nice things you're doing with myEq and if you need help.
